FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish /app/AlertsApi.TgAlerts.Worker/AlertsApi.TgAlerts.Worker.csproj -o /app/worker


FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /app
COPY --from=build /app/worker /app
ENTRYPOINT [ "dotnet", "/app/AlertsApi.TgAlerts.Worker.dll" ]