name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  API_REPO_NAME: ${{secrets.API_REPO_NAME}}
  WORKER_REPO_NAME: ${{secrets.WORKER_REPO_NAME}}
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD  
    
    - name: Build Api Image
      run: docker build . --file Dockerfile.Api --tag $DOCKER_USER/$API_REPO_NAME:latest

    - name: Push Api Image
      run: docker push $DOCKER_USER/$API_REPO_NAME:latest
      
    - name: Build Worker Image
      run: docker build . --file Dockerfile.Worker --tag $DOCKER_USER/$WORKER_REPO_NAME:latest

    - name: Push Worker Image
      run: docker push $DOCKER_USER/$WORKER_REPO_NAME:latest